### ISSUE TITLE
Make the installer work offline

### ISSUE THREAD

**Issue by oers** [baasgeo/mapproxywindows#5]
It would be nice, if the installer could work in an offline Environment.
Sometimes certain machines don't have access to the internet.

**Comment by bartbaas** [comment]
The installer *should* work offline. In fact, I use it on some production servers with no internet access.

**Comment by bartbaas** [comment]
I'm going to close this for now. But feel free to reopen if you can come up with an example with evidences that there's a problem in an offline environment.
