### ISSUE TITLE
New Data Directory on Install

### ISSUE THREAD

**Issue by xestho** [baasgeo/mapproxywindows#6]
Hi

On the installation process I wanted to create a new data directory for MapProxy. But as I saw in the code you only can change the directory to something you want if there is already a mapproxy.yaml file. It would be nice if you could choose to set a different data directory and if threre is no mapproxy.yaml file, place the init config there like to the standard data directory

**Comment by bartbaas** [comment]
Hi, normally I just copy a initial data directory from another installation but I like your idea. Feel free to send a pull request, I'll be happy to merge.
